######################################################################
# Automatically generated by qmake (3.0) ?? 6? 8 23:07:11 2014
######################################################################

TEMPLATE = app
TARGET = hello
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
