######################################################################
# Automatically generated by qmake (3.0) ?? 6? 9 13:58:28 2014
######################################################################

TEMPLATE = app
TARGET = xdf
INCLUDEPATH += .

# Input
SOURCES += xdf.cpp

QT += widgets
make
