######################################################################
# Automatically generated by qmake (3.0) ?? 6? 9 17:22:48 2014
######################################################################

TEMPLATE = app
TARGET = transparent
INCLUDEPATH += .

# Input
SOURCES += transparent.cpp

QT += widgets
make
